/**
 * FIXTURE-ONLY development catalog — NOT live web/API data.
 * Replace with backend-mediated discovery when live providers connect.
 */
import type { OpportunityCandidate } from '@/starpath/starpathOpportunityTypes';

/** Anchor for relative date shifting in discovery (FIXTURE-ONLY). */
export const FIXTURE_ANCHOR_MS = 1_700_300_000_000;
const FIXTURE_BASE = FIXTURE_ANCHOR_MS;

export const FIXTURE_OPPORTUNITY_CATALOG: OpportunityCandidate[] = [
  {
    id: 'fixture-grant-learning-01',
    title: 'Community learning micro-grant',
    opportunityType: 'grant',
    provider: 'Regional Arts Council',
    sourceName: 'FIXTURE Catalog',
    officialUrl: 'https://example.org/fixture/grant-learning',
    description: 'Small grants for skill-building projects. Review eligibility on the official site.',
    location: 'Regional',
    remoteAvailable: true,
    deadline: FIXTURE_BASE + 10 * 24 * 60 * 60 * 1000,
    eligibilitySummary: 'Open to residents pursuing creative or technical learning.',
    categories: ['learning', 'funding'],
    relatedBranchIds: ['learning'],
    relatedNodeIds: ['p-blue-1', 'sym-book'],
    reasonCodes: [],
    freshnessStatus: 'fresh',
    verificationStatus: 'fixture',
    retrievedAt: FIXTURE_BASE,
    expiresAt: FIXTURE_BASE + 11 * 24 * 60 * 60 * 1000,
    availabilityStatus: 'open',
    fixtureOnly: true,
  },
  {
    id: 'fixture-event-community-01',
    title: 'Neighborhood creative gathering',
    opportunityType: 'event',
    provider: 'Local Arts Network',
    sourceName: 'FIXTURE Catalog',
    officialUrl: 'https://example.org/fixture/event-community',
    description: 'An evening to meet makers and share works-in-progress.',
    location: 'Downtown',
    remoteAvailable: false,
    startDate: FIXTURE_BASE + 12 * 24 * 60 * 60 * 1000,
    registrationDeadline: FIXTURE_BASE + 9 * 24 * 60 * 60 * 1000,
    cost: 'Free',
    categories: ['community', 'networking'],
    relatedBranchIds: ['community'],
    relatedNodeIds: ['sym-community'],
    reasonCodes: [],
    freshnessStatus: 'fresh',
    verificationStatus: 'fixture',
    retrievedAt: FIXTURE_BASE,
    availabilityStatus: 'open',
    fixtureOnly: true,
  },
  {
    id: 'fixture-workshop-growth-01',
    title: 'Quiet momentum workshop',
    opportunityType: 'workshop',
    provider: 'Growth Circle',
    sourceName: 'FIXTURE Catalog',
    description: 'A half-day workshop on sustainable personal growth habits.',
    remoteAvailable: true,
    deadline: FIXTURE_BASE + 20 * 24 * 60 * 60 * 1000,
    categories: ['growth'],
    relatedBranchIds: ['growth'],
    relatedNodeIds: ['p-green-r1', 'sym-growth'],
    reasonCodes: [],
    freshnessStatus: 'fresh',
    verificationStatus: 'fixture',
    retrievedAt: FIXTURE_BASE,
    availabilityStatus: 'open',
    fixtureOnly: true,
  },
  {
    id: 'fixture-app-tool-learning-01',
    title: 'FocusNotes (planning tool)',
    opportunityType: 'app_tool',
    provider: 'FocusNotes Inc.',
    sourceName: 'FIXTURE Catalog',
    officialUrl: 'https://example.org/fixture/focusnotes',
    description: 'A simple tool for organizing learning projects — verify details on the official site.',
    remoteAvailable: true,
    categories: ['learning', 'tools'],
    relatedBranchIds: ['learning'],
    relatedNodeIds: ['sym-book'],
    reasonCodes: [],
    freshnessStatus: 'fresh',
    verificationStatus: 'fixture',
    retrievedAt: FIXTURE_BASE,
    availabilityStatus: 'open',
    fixtureOnly: true,
  },
];
