/** User-facing Connected Skies copy (mutual Sky follow). Internal keys may still use sky_friends. */
export const ConnectedSkiesCopy = {
  screenTitle: 'Connected Skies',
  summaryCount: (count: number) =>
    `${count} Connected Sk${count === 1 ? 'y' : 'ies'}`,
  summaryLine: 'Mutual Sky follows — you see each other’s eligible Skywrites.',
  tabConnected: 'Connected Skies',
  tabFollowing: 'Following',
  tabFollowers: 'Followers',
  emptyConnectedTitle: 'No Connected Skies yet',
  emptyConnectedBody:
    'When you and someone both follow each other’s Sky, they will appear here.',
  emptyFollowingTitle: 'Not following anyone yet',
  emptyFollowingBody: 'Following their Sky is a one-way connection until they follow you back.',
  emptyFollowersTitle: 'No one follows your Sky yet',
  emptyFollowersBody: 'When someone follows your Sky, they will appear here.',
  searchPlaceholder: 'Search by name',
  viewSky: 'View Sky',
  followSky: 'Follow Sky',
  unfollow: 'Unfollow',
  message: 'Message',
  limit: 'Limit',
  removeLimit: 'Remove limit',
  block: 'Block',
  blockedTitle: 'Blocked',
  limitedTitle: 'Limited',
  unblock: 'Unblock',
  cancel: 'Cancel',
  blockConfirmTitle: (name: string) => `Block ${name}?`,
  blockConfirmBody: 'They will not be able to follow you or see eligible shared content.',
  profileEntryTitle: 'Connected Skies',
  profileEntrySubtitle: 'Mutual Sky follows and your follow lists',
  relationshipConnected: 'Connected Sky',
  relationshipFollowing: 'Following their Sky',
  relationshipFollowsYou: 'They follow your Sky',
} as const;
