export const ContributionBeaconCopy = {
  indicatorA11y: (count: number) =>
    `${count} Sky Invitation${count === 1 ? '' : 's'}`,
  sheetTitle: 'Sky Invitations',
  sheetSubtitle: 'Reach out when something resonates.',
  invitationEyebrow: 'Someone could use your perspective ✨',
  invitationContext: (_areaLabel: string) => '',
  progress: (current: number, total: number) => `${current} of ${total}`,
  viewAll: 'View all',
  backToCard: 'One at a time',
  respond: 'Share a thought',
  notForMe: 'Not for me',
  close: 'Close',
  caughtUp: 'You’re all caught up',
  caughtUpHint: 'Peace is valid — return to your Sky when you’re ready.',
  nextBatch: (remaining: number) => `More available (${remaining} remaining)`,
  batchProgress: (globalIndex: number, total: number) => `${globalIndex} of ${total}`,
  previewFallback: 'A Skywrite may be worth your perspective.',
  responseSentAck: 'Perspective sent ✨',
} as const;
