export const FindFamiliarSkiesCopy = {
  title: 'Find your people',
  subtitle: 'Discover familiar faces or invite someone into your Sky.',
  phoneTitle: 'Phone contacts',
  phoneBody: 'Match numbers and emails from contacts you allow—never by name alone.',
  phoneAction: 'Use phone contacts',
  googleTitle: 'Google Contacts',
  googleBody: 'Works with your Google account. Sign-in and contact access are separate steps.',
  googleAction: 'Connect Google Contacts',
  googleUnavailableConfigured:
    'Google sign-in for contacts is not finished in this build. See docs/friend-discovery/GOOGLE-CONTACTS-SETUP.md for OAuth client, People API, and EXPO_PUBLIC_GOOGLE_CLIENT_ID.',
  phoneWebHint:
    'On desktop web, device contacts are not available. Use username search or invite links below—phone matching works in the Reelyou iOS/Android app after you allow contacts.',
  facebookTitle: 'Facebook',
  facebookBody: 'See Reelyou members Facebook allows us to suggest—never your whole friend list.',
  facebookAction: 'Connect Facebook',
  inviteTitle: 'Invite friends',
  inviteBody: 'Share a link by text, email, or your apps—you choose recipients and send it yourself.',
  inviteAction: 'Invite friends',
  instagramTitle: 'Invite through Instagram',
  instagramBody: 'Opens your share sheet with a Reelyou link. We do not import Instagram friends.',
  instagramAction: 'Share to Instagram',
  copyLinkAction: 'Copy link',
  smsAction: 'Text message',
  emailAction: 'Email',
  searchTitle: 'Search by username',
  searchPlaceholder: 'Search Reelyou username',
  searchHintWeb: 'Username search is available from My Sky after signup.',
  discoverabilityTitle: 'Let others find you',
  discoverabilityPhone: 'Discoverable by verified phone',
  discoverabilityPhoneHint: 'Only matched when someone you authorized shares contacts with Reelyou.',
  discoverabilityEmail: 'Discoverable by verified email',
  discoverabilityEmailHint: 'Your email is never shown in suggestions—only that you may know each other.',
  disconnectTitle: 'Imported matches',
  disconnectBody: 'Stop syncing and clear contact-based suggestions from this device.',
  disconnectAction: 'Clear imported contact data',
  disconnectGoogle: 'Disconnect Google Contacts',
  contactsUnavailableWeb:
    'Device contacts are not available in the browser. Search by username or send an invite link instead.',
  contactsAction: 'Find from contacts',
  contactsTitle: 'Phone contacts',
  contactsBody:
    'We match phone numbers and emails only against discoverable Reelyou accounts. Your address book is not stored.',
  deniedHint: 'Contacts access is off. You can try again anytime or skip for now.',
  limitedHint: 'Limited contact access—only the people you selected may be matched.',
  loading: 'Looking for familiar faces…',
  noMatches: 'No discoverable matches yet. Invite someone or explore My Sky.',
  inviteCopied: 'Invitation link copied',
  inviteOpened: 'Finish sending when your app opens—we do not send automatically.',
  skip: 'Skip for now',
  continue: 'Continue',
  settingsEntry: 'Find your people',
  exploreEntry: 'Find your people',
  googleUnavailable: 'Google Contacts is not configured in this build yet.',
  facebookUnavailable: 'Facebook matching is not available in this release.',
  cancelNote: 'Cancelled—nothing was sent.',
  errorGeneric: 'Something went wrong. You can skip and try again later.',
} as const;
