export const GuidingLightCopy = {
  sectionTitle: 'Guiding Light',
  peaceMessage: 'Nothing needs your attention right now.',
  whyThis: 'Why this?',
  whyThisA11y: 'Why this Guiding Light',
  whyTitle: 'Why this?',
  dismiss: 'Not now',
  companionLink: 'Your Guide',
  companionA11y: 'Open Your Guide',
  closeA11y: 'Close',
  companionTitle: 'Your Guide',
  companionSubtitle: 'A private space to reflect.',
  companionEmpty: 'Share a little more about yourself to open Your Guide.',
  companionBack: 'Back',
  companionPrivacyLine: "Uses only what you've chosen to share.",
  companionPermissionsLink: '',
  companionPermissionsBody: '',
  companionGuideHint: '',
  companionInputPlaceholder: 'Share what’s on your mind…',
  companionSendLabel: 'Send',
} as const;
