export const GuidingLightCopy = {
  sectionTitle: 'Guiding Light',
  peaceMessage: 'Nothing needs your attention right now.',
  whyThis: 'Why this?',
  whyThisA11y: 'Why this Guiding Light',
  whyTitle: 'Why this?',
  dismiss: 'Not now',
  companionLink: 'Companion',
  companionA11y: 'Open Companion',
  closeA11y: 'Close',
  companionTitle: 'Companion',
  companionSubtitle: 'A calm space to reflect with what you’ve shared — when you’re ready.',
  companionEmpty: 'Share a little more about yourself to open the Companion.',
  companionBack: '← Home',
  companionContextTitle: 'What the Companion can see',
  companionContextHint: 'Only what you’ve chosen to share — nothing hidden or inferred.',
} as const;
