export const MySkywritesCopy = {
  indicatorA11y: 'My Skywrites',
  sheetTitle: 'My Skywrites',
  sheetSubtitle: 'Your writing and where you have shown up.',
  listHint: 'Tap the media to watch or listen. Use ⋯ for archive and other actions.',
  tabRecent: 'Recent',
  tabYourJourney: 'Your Journey',
  tabSavedThreads: 'Saved threads',
  tabSaved: 'Saved threads',
  tabArchived: 'Archived',
  tabContributed: 'Contributed',
  emptySaved: 'Threads you save will gather here.',
  emptyYourJourney: 'Posts you add to Your Journey will stay until you remove them.',
  addToYourJourney: 'Add to Your Journey',
  addToYourJourneyHint:
    'Keep this post in Your Journey after it leaves Recent (30 days). SkyReel still runs 24 hours.',
  alreadyInYourJourney: 'In Your Journey',
  journeyAddedSuccess: 'Added to Your Journey.',
  publishAddToYourJourney: 'Add to Your Journey',
  publishAddToYourJourneyHint:
    'Optional — keeps this post in Your Journey after its 30-day Recent window. SkyReel visibility is still 24 hours.',
  searchPlaceholder: 'Search text or area…',
  emptyRecent: 'Your Skywrites will gather here.',
  emptyArchived: 'Nothing resting here yet.',
  emptyContributed: 'When you respond to others, it will appear here.',
  archiveAction: 'Rest in archive',
  restoreAction: 'Bring back',
  close: 'Close',
  repostPlaySky: 'Repost to SkyReel',
  repostPlaySkyHint: 'Starts a fresh 24-hour SkyReel window without duplicating the post.',
  repostSkyreelSuccess: 'Posted to SkyReel',
  repostSkyreelPending: 'Posting to SkyReel…',
  repostSkyreelFailed: 'Couldn’t repost to SkyReel. Try again.',
} as const;
