export const MY_SKY_TAGLINE = 'A living reflection of who you are becoming.' as const;

export const MySkyCopy = {
  title: 'My Sky ✨',
  subtitle: MY_SKY_TAGLINE,
  homeLink: '← Home',
  northStarTitle: 'North Star',
  northStarEmpty: 'Your North Star can guide what you’re moving toward.',
  northStarHint: 'What you’re moving toward',
  starsTitle: 'Stars in your sky',
  constellationsTitle: 'Patterns taking shape',
  connectionsTitle: 'Communities in your sky',
  contributionsTitle: 'Moments of contribution',
  exploreHint: 'Tap a star to sense what it might mean — possibilities emerge, then settle.',
  starInsightOpenDetail: 'Open full detail',
  starInsightBetaLabel: 'Beta example',
  identityStarTitle: 'Your Identity Star',
  identitySelfInsight:
    'This is you within your living Sky. It reflects who you are becoming as your experiences, choices, relationships, and growth evolve.',
  skywriteDetailBack: '← My Sky',
  skywriteDetailTitle: 'Your Skywrite',
  skywriteMissingTitle: 'Moment unavailable',
  skywriteMissingBody: 'This reflection is no longer in your sky.',
  starMissingToast: 'This moment is no longer available.',
  starDetailBack: '← My Sky',
  starDetailEyebrow: 'In your sky',
  starDetailPatternLabel: 'Pattern',
  starDetailContextLabel: 'About this star',
  starDetailSparseBody: 'This star holds a quiet place in your sky.',
  starDetailMissingTitle: 'Star unavailable',
  starDetailMissingBody: 'This moment is no longer visible in your sky.',
  historyTitle: 'How your sky has changed',
  historyHint: 'Meaningful moments from your journey — newest first.',
  historyEmptyTitle: 'Your history is still unfolding',
  historyEmptyBody: 'As you Skywrite, reflect, and connect, gentle changes will appear here.',
  searchTitle: 'Find a Sky',
  searchControlLabel: 'Search',
  joinedGroupsControlLabel: 'Groups',
  joinedGroupsControlA11y: 'Open your joined groups',
  joinedGroupsCoachmark: 'Your joined groups live here.',
  joinedGroupsCoachmarkA11y: 'Dismiss tip about joined groups',
  joinedGroupsSheetTitle: 'Your Groups',
  joinedGroupsSheetEmpty: 'Your joined groups will live here.',
  joinedGroupsSheetEmptyHint:
    'Emerging Groups you join will appear here for quick access.',
  joinedGroupsSheetClose: 'Close',
  constellationsControlLabel: 'Constellations',
  constellationsControlA11y: 'Show constellations in your Sky',
  constellationsCoachmark: 'See the groups forming in your Sky.',
  constellationsCoachmarkA11y: 'Dismiss tip about constellations in your Sky',
  constellationsSkyEmptyHint: 'No constellations are forming yet.',
  constellationsSheetTitle: 'Constellations in your Sky',
  constellationsSheetSubtitle: 'Visual formations tied to Emerging Groups forming around you.',
  constellationsSheetEmpty:
    'New constellations will appear here as meaningful connections begin to form.',
  constellationFormationJoined: 'Joined',
  constellationFormationForming: 'Forming',
  constellationFormationEmerging: 'Emerging',
  searchPlaceholder: 'Search friends and connected skies',
  searchEmpty: 'No Skies found yet.',
  searchClose: 'Close',
  searchGroupConnected: 'Connected',
  searchGroupSharedCommunities: 'Shared Communities',
  searchGroupExplore: 'Explore',
  searchSharedCommunity: 'Shared community',
  searchSharedIn: 'Shared in {community}',
  searchViewSky: 'View Sky',
  searchSkyUnavailable: 'Sky unavailable',
  searchSkyUnavailableBody: 'This person’s Public Sky is not available yet.',
  cleanSkyOn: 'Clean Sky',
  cleanSkyOff: 'Show controls',
  cleanSkyCompactLabel: 'Clean',
  cleanSkyHint: 'Explore your sky without overlays',
  immersiveModeEnter: 'Enter immersive full-sky mode',
  immersiveModeExit: 'Exit immersive mode and restore controls',
  exploreGestureHint: 'Drag to explore · Pinch to zoom',
  identityNorthStarPrefix: 'North Star —',
  identityViewProfile: 'View Profile',
  identityViewFullSky: 'View Full Sky',
  identityConnect: 'Connect',
  identityConnected: 'Connected',
  identityDiscoverable: 'In your orbit',
  exploreToggleLabel: 'Explore',
  exploreToggleAccessibilityOn: 'Explore is on. Wider skies visible. Tap to turn off.',
  exploreToggleAccessibilityOff: 'Explore is off. Tap to reveal wider skies.',
  exploreScrollEmpty:
    'Follow Skies you trust to scroll their snapshots here. Suggestions stay separate until you connect.',
  exploreScrollFooter: 'Scrolling Explore does not create connections or change your counts.',
  nearbyTitle: 'Nearby Skies',
  nearbySubtitle: 'Friends, connections, and shared communities in your universe.',
  nearbyEmpty: 'No connected skies nearby yet.',
  nearbyConnected: 'Connected',
  nearbySharedCommunity: 'Shared community',
  nearbyExplore: 'Public Sky',
  proximityNearby: '{name} nearby',
  proximityEntering: 'Entering {name}\u2019s Sky',
  proximityEntered: '{name}\u2019s Sky',
  proximityReturning: 'Your Sky',
  ownerSkyLabel: '{name}\u2019s Sky',
  searchJumpToSky: 'Jump to Sky',
  searchViewProfile: 'View Profile',
  nearbyChip: 'Nearby',
  constellationConnectedStars: 'Connected stars',
  constellationDetailClose: 'Close',
  publicSkyBack: '← My Sky',
  publicSkyOwnerLabel: '{name}\u2019s Sky',
  publicSkyVisitorLabel: 'Visiting',
  publicSkyGestureHint: 'Drag to explore · Tap stars to view',
  publicStarUnavailable: 'This moment is not public.',
  privacyTitle: 'Sky Visibility',
  privacySubtitle: 'Choose what others can see when they visit your Sky.',
  privacyControlLabel: 'Privacy',
  privacySkyVisibility: 'Sky Visibility',
  privacySkyVisibilityHint: 'Who can discover and open your Public Sky.',
  privacyDefaultVisibility: 'Default Visibility',
  privacyDefaultVisibilityHint: 'New stars and unset content start here.',
  privacyOverridesTitle: 'Content Overrides',
  privacyOverridesHint: 'Optional limits for specific layers.',
  privacyOverrideCommunities: 'Communities',
  privacyOverrideConnections: 'Connections',
  privacyOverrideImpact: 'Contributions',
  starIntroSkywriteTitle: 'Every Skywrite becomes a star in your Sky.',
  starIntroSkywriteBody: 'Gold is Motion. Blue is Memory. Purple is Reflection.',
  starIntroSkywriteSupport: 'Video · Photo · Text',
  starIntroMySkyTitle: 'Your Sky grows with you.',
  starIntroMySkyBody: 'Each Skywrite becomes a star. Tap a star to revisit that moment.',
  starIntroMySkyIdentity: 'Your star stays at the heart of your Sky.',
  starIntroHelpReplay: 'Understanding your stars',
  starIntroHelpReplayHint: 'Show the star color guide again on Skywrite and My Sky.',
  starIntroHelpReplayAck: 'The guide will appear the next time you open Skywrite and My Sky.',
} as const;
