export const MY_SKY_TAGLINE = 'A living reflection of who you are becoming.' as const;

export const MySkyCopy = {
  title: 'My Sky ✨',
  subtitle: MY_SKY_TAGLINE,
  homeLink: '← Home',
  northStarTitle: 'North Star',
  northStarEmpty: 'Your North Star can guide what you’re moving toward.',
  northStarHint: 'What you’re moving toward',
  starsTitle: 'Stars in your sky',
  constellationsTitle: 'Patterns taking shape',
  connectionsTitle: 'Communities in your sky',
  contributionsTitle: 'Moments of contribution',
  exploreHint: 'Tap a star to revisit a moment where a destination exists.',
  skywriteDetailBack: '← My Sky',
  skywriteDetailTitle: 'Your Skywrite',
  skywriteMissingTitle: 'Moment unavailable',
  skywriteMissingBody: 'This reflection is no longer in your sky.',
  starMissingToast: 'This moment is no longer available.',
  starDetailBack: '← My Sky',
  starDetailEyebrow: 'In your sky',
  starDetailPatternLabel: 'Pattern',
  starDetailContextLabel: 'About this star',
  starDetailSparseBody: 'This star holds a quiet place in your sky.',
  starDetailMissingTitle: 'Star unavailable',
  starDetailMissingBody: 'This moment is no longer visible in your sky.',
} as const;
