export const MY_SKY_TAGLINE = 'A living reflection of who you are becoming.' as const;

export const MySkyCopy = {
  title: 'My Sky ✨',
  subtitle: MY_SKY_TAGLINE,
  homeLink: '← Home',
  northStarTitle: 'North Star',
  northStarEmpty: 'Your North Star can guide what you’re moving toward.',
  northStarHint: 'What you’re moving toward',
  starsTitle: 'Stars in your sky',
  constellationsTitle: 'Patterns taking shape',
  connectionsTitle: 'Communities in your sky',
  contributionsTitle: 'Moments of contribution',
  exploreHint: 'Tap a star to revisit a moment where a destination exists.',
  skywriteDetailBack: '← My Sky',
  skywriteDetailTitle: 'Your Skywrite',
  skywriteMissingTitle: 'Moment unavailable',
  skywriteMissingBody: 'This reflection is no longer in your sky.',
  starMissingToast: 'This moment is no longer available.',
  starDetailBack: '← My Sky',
  starDetailEyebrow: 'In your sky',
  starDetailPatternLabel: 'Pattern',
  starDetailContextLabel: 'About this star',
  starDetailSparseBody: 'This star holds a quiet place in your sky.',
  starDetailMissingTitle: 'Star unavailable',
  starDetailMissingBody: 'This moment is no longer visible in your sky.',
  historyTitle: 'How your sky has changed',
  historyHint: 'Meaningful moments from your journey — newest first.',
  historyEmptyTitle: 'Your history is still unfolding',
  historyEmptyBody: 'As you Skywrite, reflect, and connect, gentle changes will appear here.',
  searchTitle: 'Find a Sky',
  searchControlLabel: 'Search',
  searchPlaceholder: 'Search friends and connected skies',
  searchEmpty: 'No matching skies yet. Try a name or connection.',
  searchViewSky: 'View Sky',
  searchSkyUnavailable: 'Sky unavailable',
  searchSkyUnavailableBody: 'This person’s Public Sky is not available yet.',
  cleanSkyOn: 'Clean Sky',
  cleanSkyOff: 'Show controls',
  cleanSkyCompactLabel: 'Clean',
  cleanSkyHint: 'Explore your sky without overlays',
  immersiveModeEnter: 'Enter immersive full-sky mode',
  immersiveModeExit: 'Exit immersive mode and restore controls',
  exploreGestureHint: 'Drag to explore · Pinch to zoom',
  identityNorthStarPrefix: 'North Star —',
  identityViewProfile: 'View Profile',
  identityViewFullSky: 'View Full Sky',
  identityConnect: 'Connect',
  identityConnected: 'Connected',
  identityDiscoverable: 'In your orbit',
  exploreToggleLabel: 'Explore',
  exploreToggleAccessibilityOn: 'Explore is on. Wider skies visible. Tap to turn off.',
  exploreToggleAccessibilityOff: 'Explore is off. Tap to reveal wider skies.',
  nearbyTitle: 'Nearby Skies',
  nearbySubtitle: 'Friends, connections, and shared communities in your universe.',
  nearbyEmpty: 'No connected skies nearby yet.',
  nearbyConnected: 'Connected',
  nearbySharedCommunity: 'Shared community',
  nearbyExplore: 'Public Sky',
  proximityNearby: '{name} nearby',
  proximityEntering: 'Entering {name}\u2019s Sky',
  searchJumpToSky: 'Jump to Sky',
  searchViewProfile: 'View Profile',
  nearbyChip: 'Nearby',
  constellationConnectedStars: 'Connected stars',
  constellationDetailClose: 'Close',
} as const;
