export const SavedThreadsCopy = {
  saveThread: 'Save thread',
  unsaveThread: 'Unsave thread',
  threadSaved: 'Thread saved',
  archiveSaved: 'Rest in archive',
  restoreSaved: 'Bring back',
  sectionSinceThen: 'Since then',
  choiceYes: 'Yes',
  choiceALittle: 'A little',
  choiceNotReally: 'Not really',
  skipForNow: 'Skip for now',
  optionalFollowUp: 'Optional — only if you want to',
  followUpPlaceholder: 'A few words…',
  saveMoment: 'Save',
  addMomentLink: 'Add a moment from since then',
  editMoment: 'Edit',
  deleteMoment: 'Delete',
  recordVoice: 'Quick voice',
  saveVoice: 'Save voice',
  playVoice: 'Play voice note',
  voiceMomentLabel: 'Voice note',
  evidenceAdd: 'Add',
  evidenceNotNow: 'Not now',
  evidenceSuggestionFooter: 'This is a suggestion — you’re always in control.',
  contributionMarker: 'Contribution saved',
  unsaveConfirmTitle: 'Unsave this thread?',
  unsaveConfirmBody: 'Your private moments can stay unless you choose to remove them.',
  unsaveKeepReflections: 'Unsave, keep moments',
  unsaveRemoveAll: 'Remove everything',
  cancelEdit: 'Cancel',
  detailBack: 'Back',
  inaccessibleSource: 'This conversation is no longer available.',
  inaccessibleHint: 'Your private moments remain here for you.',
} as const;
