export const SkyFriendsCopy = {
  screenTitle: 'Sky Friends',
  summaryCount: (count: number) => `${count} Sky Friend${count === 1 ? '' : 's'}`,
  summaryLine: 'People whose Sky you follow and who follow yours back.',
  tabFriends: 'Sky Friends',
  tabFollowing: 'Following',
  tabFollowers: 'Followers',
  searchPlaceholder: 'Search by name',
  emptyFriendsTitle: 'No Sky Friends yet',
  emptyFriendsBody:
    'When someone follows your Sky and you follow theirs, they’ll appear here.',
  emptyFollowingTitle: 'Not following any Skys yet',
  emptyFollowingBody: 'Skys you follow will appear here.',
  emptyFollowersTitle: 'No followers yet',
  emptyFollowersBody: 'People who follow your Sky will appear here.',
  viewSky: 'View Sky',
  message: 'Message',
  followSky: 'Follow Sky',
  following: 'Following',
  unfollow: 'Unfollow',
  limit: 'Limit',
  removeLimit: 'Remove limit',
  block: 'Block',
  blockConfirmTitle: (name: string) => `Block ${name}?`,
  blockConfirmBody:
    'They won’t be able to follow your Sky or see your REELYOU activity where blocking applies.',
  cancel: 'Cancel',
  profileEntryTitle: 'Sky Friends',
  profileEntrySubtitle: 'People following each other’s Skys',
  blockedTitle: 'Blocked people',
  limitedTitle: 'Limited people',
  unblock: 'Unblock',
} as const;
