import { ConnectedSkiesCopy } from '@/constants/connectedSkiesCopy';

/** Stable import path — user-facing strings live in ConnectedSkiesCopy. */
export const SkyFriendsCopy = {
  screenTitle: ConnectedSkiesCopy.screenTitle,
  summaryCount: ConnectedSkiesCopy.summaryCount,
  summaryLine: ConnectedSkiesCopy.summaryLine,
  tabFriends: ConnectedSkiesCopy.tabConnected,
  tabFollowing: ConnectedSkiesCopy.tabFollowing,
  tabFollowers: ConnectedSkiesCopy.tabFollowers,
  searchPlaceholder: ConnectedSkiesCopy.searchPlaceholder,
  emptyFriendsTitle: ConnectedSkiesCopy.emptyConnectedTitle,
  emptyFriendsBody: ConnectedSkiesCopy.emptyConnectedBody,
  emptyFollowingTitle: ConnectedSkiesCopy.emptyFollowingTitle,
  emptyFollowingBody: ConnectedSkiesCopy.emptyFollowingBody,
  emptyFollowersTitle: ConnectedSkiesCopy.emptyFollowersTitle,
  emptyFollowersBody: ConnectedSkiesCopy.emptyFollowersBody,
  viewSky: ConnectedSkiesCopy.viewSky,
  message: ConnectedSkiesCopy.message,
  followSky: ConnectedSkiesCopy.followSky,
  following: ConnectedSkiesCopy.relationshipFollowing,
  unfollow: ConnectedSkiesCopy.unfollow,
  limit: ConnectedSkiesCopy.limit,
  removeLimit: ConnectedSkiesCopy.removeLimit,
  block: ConnectedSkiesCopy.block,
  blockConfirmTitle: ConnectedSkiesCopy.blockConfirmTitle,
  blockConfirmBody: ConnectedSkiesCopy.blockConfirmBody,
  cancel: ConnectedSkiesCopy.cancel,
  profileEntryTitle: ConnectedSkiesCopy.profileEntryTitle,
  profileEntrySubtitle: ConnectedSkiesCopy.profileEntrySubtitle,
  blockedTitle: ConnectedSkiesCopy.blockedTitle,
  limitedTitle: ConnectedSkiesCopy.limitedTitle,
  unblock: ConnectedSkiesCopy.unblock,
} as const;
