export const SkywriteCopy = {
  title: 'Skywrite',
  subtitle: 'Your truth. Your way. Your sky.',
  reflectionLabel: 'Reflection Prompt',
  reflectionDefault: 'What are you carrying today?',
  refresh: 'Refresh',
  writePlaceholder: 'Write your sky...',
  charLimit: 1500,
  showingUpTitle: 'How are you showing up?',
  clearExpression: 'Clear selection',
  textStyleTitle: 'Text style',
  textStyleOptional: 'Optional',
  hashtagsTitle: 'Add hashtags',
  hashtagsOptional: 'Optional',
  hashtagsPlaceholder: 'Add up to 5 hashtags…',
  moreOptionsTitle: 'More options',
  aiPermissionTitle: 'Help personalize my REELYOU experience',
  aiPermissionDescription:
    'Allows this Skywrite to help REELYOU understand what may be relevant to your journey.',
  animateTitle: 'Watch this become a star',
  animateDescription: 'See this Skywrite rise into your Sky after sharing.',
  mediaPhoto: 'Photo',
  mediaVoice: 'Voice',
  mediaChangePhoto: 'Change Photo',
  mediaAddVoiceover: 'Add Voiceover',
  mediaAddPhoto: 'Add Photo',
  mediaVoiceNoteDone: 'Voice Note ✓',
  mediaReRecordVoiceover: 'Re-record Voiceover',
  photoSourceTitle: 'Add a photo',
  photoChooseLibrary: 'Choose from Library',
  photoTakePhoto: 'Take Photo',
  photoLibraryDenied: 'Photo library access is needed to choose a photo.',
  cameraDenied: 'Camera access is needed to take a photo.',
  photoWebUnavailable: 'Photo selection is unavailable in this preview.',
  microphoneDenied: 'Microphone access is needed to record a voice note.',
  voiceNoteTitle: 'Voice Note',
  voiceoverTitle: 'Voiceover',
  voiceNoteIdleHint: 'Tap record to capture what you cannot easily type.',
  voiceoverIdleHint: 'Tap record to add your voice to this moment.',
  record: 'Record',
  recordingLabel: 'Recording',
  pause: 'Pause',
  resume: 'Resume',
  reRecordVoiceNote: 'Re-record',
  reRecordVoiceover: 'Re-record',
  stop: 'Stop',
  cancel: 'Cancel',
  voiceoverBadge: 'Voiceover',
  removeVoiceover: 'Remove voiceover',
  removeMedia: 'Remove',
  emptyValidation: 'Add something to your Sky first.',
  shareHint: 'When you share, a star will light the sky ✨',
  shareButton: '✨ Share to Sky',
  shareFooter: 'Your words can light someone’s path.',
  shareInAreaTitle: 'Share this in…',
  shareInAreaHint: 'Choose one area for this Skywrite — used for threads and contribution beacons.',
  beaconTransparency:
    'Shown from an area you said you’re open to contributing in.',
  respond: 'Respond',
  ignoreBeacon: 'Not for me',
  saveResponse: 'Save Response',
  unsaveResponse: 'Unsave',
  threadResponsesTitle: 'Responses',
  threadResponsePlaceholder: 'Share perspective from your experience…',
  threadSubmitResponse: 'Send response',
  authorBeaconResolved: 'I got what I needed',
  authorBeaconReopen: 'Keep looking for perspective',
  successTitle: 'Your reflection became a star in your sky.',
  successAnimateHint: 'Your moment is ready to rise into your Sky.',
  successReturn: 'Return Home',
} as const;

export const SKYWRITE_REFLECTION_PROMPTS = [
  'What are you carrying today?',
  'What has been on your mind lately?',
  'What felt meaningful today?',
  'What are you learning about yourself?',
  'What do you want to remember from today?',
  'What feels different lately?',
] as const;

export const SKYWRITE_SHOWING_UP_OPTIONS = [
  { id: 'reflection', label: 'Reflection', emoji: '✨', color: '#A78BFA' },
  { id: 'growth', label: 'Growth', emoji: '🌱', color: '#5EEAD4' },
  { id: 'gratitude', label: 'Gratitude', emoji: '💗', color: '#E879A8' },
  { id: 'encouragement', label: 'Encouragement', emoji: '🤝', color: '#5BC0FF' },
  { id: 'struggle', label: 'Struggle', emoji: '🌧️', color: '#E8843A' },
  { id: 'breakthrough', label: 'Breakthrough', emoji: '🔥', color: '#F5D76E' },
  { id: 'question', label: 'Question', emoji: '❓', color: '#C4A8FF' },
  { id: 'processing', label: 'Processing', emoji: '🧠', color: '#5EEAD4' },
] as const;

export type SkywriteShowingUpId = (typeof SKYWRITE_SHOWING_UP_OPTIONS)[number]['id'];

export const SKYWRITE_VISIBILITY_OPTIONS = [
  {
    id: 'public' as const,
    title: 'Public Sky',
    subtitle: 'Everyone',
    collapsed: 'Public Sky · Everyone',
    icon: '🌐',
  },
  {
    id: 'orbit' as const,
    title: 'Constellations Only',
    subtitle: "Communities you're in",
    collapsed: 'Constellations Only · Communities',
    icon: '👥',
  },
  {
    id: 'private' as const,
    title: 'Private Reflection',
    subtitle: 'Only you',
    collapsed: 'Private Reflection · Only you',
    icon: '🔒',
  },
] as const;
