export const SkywriteCopy = {
  title: 'Skywrite',
  subtitle: 'Your truth. Your way. Your sky.',
  reflectionLabel: 'Reflection Prompt',
  reflectionDefault: 'What are you carrying today?',
  refresh: 'Refresh',
  writePlaceholder: 'Write your sky...',
  charLimit: 1500,
  showingUpTitle: 'How are you showing up?',
  clearExpression: 'Clear selection',
  textStyleTitle: 'Text style',
  textStyleOptional: 'Optional',
  hashtagsTitle: 'Add hashtags',
  hashtagsOptional: 'Optional',
  hashtagsPlaceholder: 'Add up to 5 hashtags…',
  moreOptionsTitle: 'More options',
  aiPermissionTitle: 'Help personalize my REELYOU experience',
  aiPermissionDescription:
    'Allows this Skywrite to help REELYOU understand what may be relevant to your journey.',
  animateTitle: 'Watch this become a star',
  animateDescription: 'See this Skywrite rise into your Sky after sharing.',
  mediaPhoto: 'Photo',
  mediaVideo: 'Video',
  mediaChangeVideo: 'Change Video',
  mediaVoice: 'Voice',
  mediaChangePhoto: 'Change Photo',
  mediaAddVoiceover: 'Add Voiceover',
  mediaAddPhoto: 'Add Photo',
  mediaVoiceNoteDone: 'Voice Note ✓',
  mediaReRecordVoiceover: 'Re-record Voiceover',
  photoSourceTitle: 'Add a photo',
  photoChooseLibrary: 'Choose from Library',
  photoTakePhoto: 'Take Photo',
  photoLibraryDenied: 'Photo library access is needed to choose a photo.',
  cameraDenied: 'Camera access is needed to take a photo.',
  photoWebUnavailable: 'Photo selection is unavailable in this preview.',
  videoSourceTitle: 'Add a video',
  videoChooseLibrary: 'Choose from Library',
  videoRecord: 'Record Video',
  videoLibraryDenied: 'We couldn’t access your photo library.',
  videoCameraDenied: 'We couldn’t access your camera.',
  videoWebUnavailable: 'Video selection is unavailable in this preview.',
  videoTooLong: 'That video is a bit long for now. Try a shorter clip.',
  videoUnsupported: 'We couldn’t use that video. Try another file.',
  videoOriginalAudioOn: 'Original audio: On',
  videoOriginalAudioLower: 'Original audio: Lower',
  videoOriginalAudioOff: 'Original audio: Off',
  videoOriginalSoundTitle: 'Original video sound',
  videoOriginalSoundHint: 'Adjust separately from your voiceover. Levels apply in preview and after posting.',
  videoOriginalMute: 'Mute original',
  videoOriginalUnmute: 'Unmute original',
  videoFramingFit: 'Fit',
  videoFramingFill: 'Fill',
  videoFramingAdjust: 'Adjust framing',
  videoFramingReset: 'Reset framing',
  videoFramingAdjusting: 'Drag to reposition',
  videoFramingFillHint:
    'Fit shows the full frame. Switch to Fill to drag and re-center without stretching.',
  videoFramingLongPressHint: 'Press and hold to adjust framing',
  videoFramingDone: 'Done',
  videoFramingNoOverflowHint:
    'This clip has no extra room to pan in Fill on this screen. Try a different aspect or use Fit for the full frame.',
  videoFramingNoHorizontalPan: 'No horizontal room to pan in Fill for this clip.',
  videoFramingNoVerticalPan: 'No vertical room to pan in Fill for this clip.',
  editSkywriteSave: 'Save changes',
  editSkywriteTitle: 'Edit Skywrite',
  microphoneDenied: 'We couldn’t access your microphone.',
  microphoneDeniedHint: 'You can enable access or choose another media option.',
  voiceNoteTitle: 'Voice Note',
  voiceoverTitle: 'Voiceover',
  voiceNoteIdleHint: 'Tap record to capture what you cannot easily type.',
  voiceoverIdleHint: 'Tap record to add your voice to this moment.',
  record: 'Record',
  recordingLabel: 'Recording',
  pause: 'Pause',
  resume: 'Resume',
  reRecordVoiceNote: 'Re-record',
  reRecordVoiceover: 'Re-record',
  stop: 'Stop',
  cancel: 'Cancel',
  voiceoverBadge: 'Voiceover',
  removeVoiceover: 'Remove voiceover',
  removeMedia: 'Remove',
  emptyValidation: 'Add something to your Sky first.',
  previewButton: 'Preview',
  postButton: 'Post',
  previewTitle: 'Preview your Skywrite',
  previewHint: 'This is how others will experience your post.',
  previewBackToEdit: 'Back to editing',
  previewPost: 'Post to Sky',
  commentsTitle: 'Comments',
  commentPlaceholder: 'Share a thoughtful comment…',
  commentSend: 'Send',
  commentSendError: 'We couldn’t send that comment. Try again.',
  commentForbidden: 'Comments aren’t available on this Skywrite.',
  deleteOwnComment: 'Delete',
  publishError: 'We couldn’t post your Skywrite. Please try again.',
  publishing: 'Posting…',
  publishingUploading: 'Uploading media…',
  publishingFinalizing: 'Posting…',
  publishingElapsed: (seconds: number) => `Posting… ${seconds}s`,
  publishingPhase: (phase: string, seconds: number) => `${phase.replace(/…$/, '')}… ${seconds}s`,
  publishingSuccess: 'Posted to Sky',
  shareHint: 'Preview first, then post when it feels right ✨',
  shareButton: '✨ Share to Sky',
  shareFooter: 'Your words can light someone’s path.',
  shareInAreaTitle: 'Share this in…',
  shareInAreaHint: 'Choose one area for this Skywrite — used for threads and contribution beacons.',
  beaconTransparency:
    'Suggested from an area you said you’re open to contributing in. You’re never obligated to respond.',
  respond: 'Share a thought',
  invitationEyebrow: 'Someone could use your perspective ✨',
  invitationWhyThis: 'Why this? ✨',
  invitationWhyBody: 'Suggested from your chosen areas. You’re always in control.',
  invitationComposerHint: 'Share what helped you.',
  ignoreBeacon: 'Not for me',
  sendPerspective: 'Send',
  perspectiveSent: 'Perspective sent ✨',
  saveResponse: 'Save Response',
  unsaveResponse: 'Unsave',
  saveThread: 'Save thread',
  unsaveThread: 'Unsave thread',
  openSavedThread: 'Open saved thread',
  threadResponsesTitle: 'Perspectives',
  threadResponsePlaceholder: 'What would you tell them?',
  threadSubmitResponse: 'Send',
  authorBeaconResolved: 'I got what I needed',
  authorBeaconReopen: 'Keep looking for perspective',
  successTitle: 'Your reflection became a star in your sky.',
  successAnimateHint: 'Your moment is ready to rise into your Sky.',
  successReturn: 'Return Home',
} as const;

export const SKYWRITE_REFLECTION_PROMPTS = [
  'What are you carrying today?',
  'What has been on your mind lately?',
  'What felt meaningful today?',
  'What are you learning about yourself?',
  'What do you want to remember from today?',
  'What feels different lately?',
] as const;

export const SKYWRITE_SHOWING_UP_OPTIONS = [
  { id: 'reflection', label: 'Reflection', emoji: '✨', color: '#A78BFA' },
  { id: 'growth', label: 'Growth', emoji: '🌱', color: '#5EEAD4' },
  { id: 'gratitude', label: 'Gratitude', emoji: '💗', color: '#E879A8' },
  { id: 'encouragement', label: 'Encouragement', emoji: '🤝', color: '#5BC0FF' },
  { id: 'struggle', label: 'Struggle', emoji: '🌧️', color: '#E8843A' },
  { id: 'breakthrough', label: 'Breakthrough', emoji: '🔥', color: '#F5D76E' },
  { id: 'question', label: 'Question', emoji: '❓', color: '#C4A8FF' },
  { id: 'processing', label: 'Processing', emoji: '🧠', color: '#5EEAD4' },
] as const;

export type SkywriteShowingUpId = (typeof SKYWRITE_SHOWING_UP_OPTIONS)[number]['id'];

export const SKYWRITE_VISIBILITY_OPTIONS = [
  {
    id: 'private' as const,
    title: 'Private',
    subtitle: 'Only you can see this.',
    collapsed: 'Private · Only you',
    icon: '🔒',
  },
  {
    id: 'sky_friends' as const,
    title: 'Connected Skies',
    subtitle: 'Only you and your Connected Skies can see this.',
    collapsed: 'Connected Skies · Mutual follows',
    icon: '✨',
  },
  {
    id: 'public' as const,
    title: 'Public',
    subtitle: 'People across REELYOU may see this based on where you shared it.',
    collapsed: 'Public · REELYOU',
    icon: '🌐',
  },
] as const;
