export const SkywritePlayCopy = {
  playSky: 'Play Sky',
  playHint: 'Tap a star or press play to let your Sky unfold.',
  skySubtitle: 'Your moments, arranged in a living sky.',
  editSequence: 'Edit sequence',
  sequenceTitle: 'Play sequence',
  sequenceHint: 'Choose order and which moments play — your star map stays the same.',
  include: 'Include',
  exclude: 'Skip in play',
  moveUp: 'Move up',
  moveDown: 'Move down',
  close: 'Close',
  exitPlay: 'Back to Sky',
  previous: 'Previous',
  next: 'Next',
  progress: (current: number, total: number) => `${current} of ${total}`,
  emptySequence: 'Add a Skywrite to play your Sky in sequence.',
  playSkyEmptyOwnerHint:
    'Posts stay in Skywritings after 24 hours — repost one from My Skywrites to play it again.',
  pause: 'Pause',
  resume: 'Resume',
  tapToPlaySky: 'Tap to start Play Sky (sound requires your tap in the browser)',
  addSkywrite: 'Add a Skywrite',
  openMySkywrites: 'Open My Skywrites',
  exploreFullSkySelf: 'Explore your full Sky',
  exploreFullSkyVisitor: (name: string) => `Explore ${name}'s full Sky`,
  stepText: 'Reflection',
  stepPhoto: 'Image',
  stepAudio: 'Voice',
} as const;
