export const SkywritePlayCopy = {
  playSky: 'Play Sky',
  playHint: 'Tap a star or press play to let your Sky unfold.',
  skySubtitle: 'Your moments, arranged in a living sky.',
  editSequence: 'Edit sequence',
  sequenceTitle: 'Play sequence',
  sequenceHint: 'Choose order and which moments play — your star map stays the same.',
  include: 'Include',
  exclude: 'Skip in play',
  moveUp: 'Move up',
  moveDown: 'Move down',
  close: 'Close',
  exitPlay: 'Back to Sky',
  previous: 'Previous',
  next: 'Next',
  progress: (current: number, total: number) => `${current} of ${total}`,
  emptySequence: 'Add a Skywrite to play your Sky in sequence.',
  stepText: 'Reflection',
  stepPhoto: 'Image',
  stepAudio: 'Voice',
} as const;
