export const TodayFocusCopy = {
  title: 'Today\u2019s Focus',
  subtitle: 'Choose one calm intention for today. There is no score to keep and nothing to finish.',
  suggestionsTitle: 'Suggestions for you',
  suggestionsNote: 'These are gentle starting points — your choice always comes first.',
  customTitle: 'Write your own',
  customPlaceholder: 'What deserves your attention today?',
  setFocusCta: 'Set as today\u2019s focus',
  clearFocusCta: 'Clear today\u2019s focus',
  back: '\u2190 Back',
  reflectionTitle: 'Reflection',
  reflectionPrompt: 'What habit or belief are you building today?',
  reflectionContextLabel: 'Today\u2019s Focus',
  reflectionPlaceholder: 'Write a short reflection...',
  reflectionSaveCta: 'Save',
  reflectionCancel: 'Cancel',
} as const;
