import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const banner =
  'PRIVATE BETA DRAFT — NOT FINAL LEGAL TEXT\n\n' +
  'For invited U.S. testers only (18+). Formal counsel review is required before public or commercial launch.\n\n';

function stripMd(raw) {
  return raw
    .replace(/^#+ /gm, '')
    .replace(/^\*\*Status:\*\*.*$/gm, '')
    .replace(/^---$/gm, '')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\\([_*[\]()#+.!-])/g, '$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

const tos = stripMd(fs.readFileSync(path.join(root, 'docs/legal/DRAFT-private-beta-terms-of-service.md'), 'utf8'));
const privacy = stripMd(
  fs.readFileSync(path.join(root, 'docs/legal/DRAFT-private-beta-privacy-policy.md'), 'utf8'),
);

const out = `/** Generated by scripts/syncLegalDraftContent.mjs — not final approved legal text. */
export const LEGAL_DOCUMENT_DRAFT_VERSION = '2026-10-01-beta-draft';
export const LEGAL_DOCUMENT_REQUIRES_COUNSEL = true;

export const BETA_DRAFT_BANNER = ${JSON.stringify(banner.trim())};

export const BETA_DRAFT_TERMS_BODY = ${JSON.stringify(tos)};

export const BETA_DRAFT_PRIVACY_BODY = ${JSON.stringify(privacy)};
`;

fs.writeFileSync(path.join(root, 'src/constants/legalDocumentsBetaDraftContent.ts'), out);
console.log('Synced legal draft content', { tosLen: tos.length, privacyLen: privacy.length });
